### ISSUE TITLE
Join the one click install main window with the installation progress window

### ISSUE THREAD

**Issue by jardel20** [yast/yast-yast2#1231]
When using one click install, two windows are opened until the task is finished. The installation progress window could be the same as the main window that opens. this main window is empty during the installation progress.

**Comment by dgdavid** [comment]
Hi, thanks for the report.

In order to illustrate better what you mean (and somehow verifying I understood your concern), see below screenshots

---

<p align="center"><em>YaST2 1 Click installer window</em></p>

![yast2-1click-install-](https://user-images.githubusercontent.com/1691872/148946238-76efd2be-0400-40af-880a-fe37b6f9de77.png)

---

<p align="center"><em>YaST2 1 Click installer progress windows</em></p>

![yast2-1click-install-progress](https://user-images.githubusercontent.com/1691872/148946387-12dc294d-06e8-4e4d-8f3f-7cdbed78377c.png)

---

<p align="center"><em>YaST2 1 Click installer main window is actually empty</em></p>

![Empty YaST2 1 Click installer main window](https://user-images.githubusercontent.com/1691872/148947338-96d0ef0b-2ddc-416b-b0e4-cc61ca67e6a7.png)

---

So, you'd like to _embed_ the progress in the YaST2 1 Click installer _wizard_, which makes sense. However, I believe there are reasons why it is not already _merged_ but I hadrly remember them.

@lslezak, could you help here? Thanks in advance.

**Comment by jardel20** [comment]
Exactly @dgdavid

**Comment by lslezak** [comment]
The one click installer has two parts and each of them runs with different privileges.

The first part downloads and processes the XML from the browser. This file contains the repository definitions and the list of packages to install. This part runs as the user who clicked the link in the browser.

The other part which really starts the package installation runs as administrator (the `root` user) to be able to install the packages and modify the system. Obviously this process cannot display the progress in the window belonging to a different user.

This separation is done for security reasons, the part which interacts with the browser should not run with admin privileges.

The only thing we could do is to close the first window while the other one is running. But maybe that would be still confusing as the progress from the first window would be lost...

I'm closing the issue, there are security reasons for this separation.

**Comment by dgdavid** [comment]
Thanks for the explanation @lslezak!

**Comment by jardel20** [comment]
Thanks for explanation @lslezak !!!

**Comment by awerlang** [comment]
> The other part which really starts the package installation runs as administrator (the `root` user) to be able to install the packages and modify the system. Obviously this process cannot display the progress in the window belonging to a different user.
> 
> This separation is done for security reasons, the part which interacts with the browser should not run with admin privileges.

@lslezak Is it possible to keep a 2-process model, each process performing roles as described above, with a slight change to the reporting of progress:

1. The privileged process doesn't have a GUI of its own;
2. Instead, the privileged process reports back to the caller through stdout or another appropriate RPC method;
3. The unprivileged process receives progress and updates the original window with textual/progress bars.

I'm not familiar with the codebase, but would this be feasible while respecting security practices?

**Comment by jardel20** [comment]
@lslezak Can the last comment cause the issue to be opened again?
